### ISSUE TITLE
Create osx-arm64 package

### ISSUE THREAD

**Issue by juanfcocontreras** [conda-forge/mpire-feedstock#18]
### Comment:

mpire is not available for osx-arm64

Is there any technical reason?

**Comment by synapticarbors** [comment]
Sorry for missing this issue. I don't think there would be a technical reason not to. I'll open the appropriate PR

**Comment by synapticarbors** [comment]
Actually this is a `noarch: python` package so there's no need to have a specific osx-arm64 build.
